// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module srcnn_load_conv2_params_Pipeline_VITIS_LOOP_163_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_w2_AWVALID,
        m_axi_gmem_w2_AWREADY,
        m_axi_gmem_w2_AWADDR,
        m_axi_gmem_w2_AWID,
        m_axi_gmem_w2_AWLEN,
        m_axi_gmem_w2_AWSIZE,
        m_axi_gmem_w2_AWBURST,
        m_axi_gmem_w2_AWLOCK,
        m_axi_gmem_w2_AWCACHE,
        m_axi_gmem_w2_AWPROT,
        m_axi_gmem_w2_AWQOS,
        m_axi_gmem_w2_AWREGION,
        m_axi_gmem_w2_AWUSER,
        m_axi_gmem_w2_WVALID,
        m_axi_gmem_w2_WREADY,
        m_axi_gmem_w2_WDATA,
        m_axi_gmem_w2_WSTRB,
        m_axi_gmem_w2_WLAST,
        m_axi_gmem_w2_WID,
        m_axi_gmem_w2_WUSER,
        m_axi_gmem_w2_ARVALID,
        m_axi_gmem_w2_ARREADY,
        m_axi_gmem_w2_ARADDR,
        m_axi_gmem_w2_ARID,
        m_axi_gmem_w2_ARLEN,
        m_axi_gmem_w2_ARSIZE,
        m_axi_gmem_w2_ARBURST,
        m_axi_gmem_w2_ARLOCK,
        m_axi_gmem_w2_ARCACHE,
        m_axi_gmem_w2_ARPROT,
        m_axi_gmem_w2_ARQOS,
        m_axi_gmem_w2_ARREGION,
        m_axi_gmem_w2_ARUSER,
        m_axi_gmem_w2_RVALID,
        m_axi_gmem_w2_RREADY,
        m_axi_gmem_w2_RDATA,
        m_axi_gmem_w2_RLAST,
        m_axi_gmem_w2_RID,
        m_axi_gmem_w2_RFIFONUM,
        m_axi_gmem_w2_RUSER,
        m_axi_gmem_w2_RRESP,
        m_axi_gmem_w2_BVALID,
        m_axi_gmem_w2_BREADY,
        m_axi_gmem_w2_BRESP,
        m_axi_gmem_w2_BID,
        m_axi_gmem_w2_BUSER,
        i,
        trunc_ln165,
        conv2_weights_local_0_0_address1,
        conv2_weights_local_0_0_ce1,
        conv2_weights_local_0_0_we1,
        conv2_weights_local_0_0_d1,
        conv2_weights_local_0_1_address1,
        conv2_weights_local_0_1_ce1,
        conv2_weights_local_0_1_we1,
        conv2_weights_local_0_1_d1,
        conv2_weights_local_1_0_address1,
        conv2_weights_local_1_0_ce1,
        conv2_weights_local_1_0_we1,
        conv2_weights_local_1_0_d1,
        conv2_weights_local_1_1_address1,
        conv2_weights_local_1_1_ce1,
        conv2_weights_local_1_1_we1,
        conv2_weights_local_1_1_d1,
        zext_ln161_2,
        sext_ln161,
        trunc_ln161_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_w2_AWVALID;
input   m_axi_gmem_w2_AWREADY;
output  [63:0] m_axi_gmem_w2_AWADDR;
output  [0:0] m_axi_gmem_w2_AWID;
output  [31:0] m_axi_gmem_w2_AWLEN;
output  [2:0] m_axi_gmem_w2_AWSIZE;
output  [1:0] m_axi_gmem_w2_AWBURST;
output  [1:0] m_axi_gmem_w2_AWLOCK;
output  [3:0] m_axi_gmem_w2_AWCACHE;
output  [2:0] m_axi_gmem_w2_AWPROT;
output  [3:0] m_axi_gmem_w2_AWQOS;
output  [3:0] m_axi_gmem_w2_AWREGION;
output  [0:0] m_axi_gmem_w2_AWUSER;
output   m_axi_gmem_w2_WVALID;
input   m_axi_gmem_w2_WREADY;
output  [31:0] m_axi_gmem_w2_WDATA;
output  [3:0] m_axi_gmem_w2_WSTRB;
output   m_axi_gmem_w2_WLAST;
output  [0:0] m_axi_gmem_w2_WID;
output  [0:0] m_axi_gmem_w2_WUSER;
output   m_axi_gmem_w2_ARVALID;
input   m_axi_gmem_w2_ARREADY;
output  [63:0] m_axi_gmem_w2_ARADDR;
output  [0:0] m_axi_gmem_w2_ARID;
output  [31:0] m_axi_gmem_w2_ARLEN;
output  [2:0] m_axi_gmem_w2_ARSIZE;
output  [1:0] m_axi_gmem_w2_ARBURST;
output  [1:0] m_axi_gmem_w2_ARLOCK;
output  [3:0] m_axi_gmem_w2_ARCACHE;
output  [2:0] m_axi_gmem_w2_ARPROT;
output  [3:0] m_axi_gmem_w2_ARQOS;
output  [3:0] m_axi_gmem_w2_ARREGION;
output  [0:0] m_axi_gmem_w2_ARUSER;
input   m_axi_gmem_w2_RVALID;
output   m_axi_gmem_w2_RREADY;
input  [31:0] m_axi_gmem_w2_RDATA;
input   m_axi_gmem_w2_RLAST;
input  [0:0] m_axi_gmem_w2_RID;
input  [8:0] m_axi_gmem_w2_RFIFONUM;
input  [0:0] m_axi_gmem_w2_RUSER;
input  [1:0] m_axi_gmem_w2_RRESP;
input   m_axi_gmem_w2_BVALID;
output   m_axi_gmem_w2_BREADY;
input  [1:0] m_axi_gmem_w2_BRESP;
input  [0:0] m_axi_gmem_w2_BID;
input  [0:0] m_axi_gmem_w2_BUSER;
input  [4:0] i;
input  [0:0] trunc_ln165;
output  [8:0] conv2_weights_local_0_0_address1;
output   conv2_weights_local_0_0_ce1;
output   conv2_weights_local_0_0_we1;
output  [31:0] conv2_weights_local_0_0_d1;
output  [8:0] conv2_weights_local_0_1_address1;
output   conv2_weights_local_0_1_ce1;
output   conv2_weights_local_0_1_we1;
output  [31:0] conv2_weights_local_0_1_d1;
output  [8:0] conv2_weights_local_1_0_address1;
output   conv2_weights_local_1_0_ce1;
output   conv2_weights_local_1_0_we1;
output  [31:0] conv2_weights_local_1_0_d1;
output  [8:0] conv2_weights_local_1_1_address1;
output   conv2_weights_local_1_1_ce1;
output   conv2_weights_local_1_1_we1;
output  [31:0] conv2_weights_local_1_1_d1;
input  [10:0] zext_ln161_2;
input  [61:0] sext_ln161;
input  [0:0] trunc_ln161_2;

reg ap_idle;
reg m_axi_gmem_w2_ARVALID;
reg m_axi_gmem_w2_RREADY;
reg conv2_weights_local_0_0_ce1;
reg conv2_weights_local_0_0_we1;
reg conv2_weights_local_0_1_ce1;
reg conv2_weights_local_0_1_we1;
reg conv2_weights_local_1_0_ce1;
reg conv2_weights_local_1_0_we1;
reg conv2_weights_local_1_1_ce1;
reg conv2_weights_local_1_1_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln163_fu_220_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_w2_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem_w2_blk_n_R;
wire   [0:0] trunc_ln161_2_read_reg_317;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln163_fu_236_p1;
reg   [0:0] trunc_ln163_reg_335;
reg   [0:0] trunc_ln163_reg_335_pp0_iter1_reg;
reg   [0:0] trunc_ln163_reg_335_pp0_iter2_reg;
reg   [0:0] trunc_ln163_reg_335_pp0_iter3_reg;
reg   [0:0] trunc_ln163_reg_335_pp0_iter4_reg;
reg   [0:0] trunc_ln163_reg_335_pp0_iter5_reg;
reg   [0:0] trunc_ln163_reg_335_pp0_iter6_reg;
reg   [0:0] trunc_ln163_reg_335_pp0_iter7_reg;
reg   [0:0] trunc_ln163_reg_335_pp0_iter8_reg;
reg   [0:0] trunc_ln163_reg_335_pp0_iter9_reg;
reg   [4:0] lshr_ln2_reg_339;
reg   [4:0] lshr_ln2_reg_339_pp0_iter1_reg;
reg   [4:0] lshr_ln2_reg_339_pp0_iter2_reg;
reg   [4:0] lshr_ln2_reg_339_pp0_iter3_reg;
reg   [4:0] lshr_ln2_reg_339_pp0_iter4_reg;
reg   [4:0] lshr_ln2_reg_339_pp0_iter5_reg;
reg   [4:0] lshr_ln2_reg_339_pp0_iter6_reg;
reg   [4:0] lshr_ln2_reg_339_pp0_iter7_reg;
reg   [4:0] lshr_ln2_reg_339_pp0_iter8_reg;
reg   [4:0] lshr_ln2_reg_339_pp0_iter9_reg;
reg   [63:0] gmem_w2_addr_reg_344;
wire   [31:0] bitcast_ln165_fu_281_p1;
reg   [31:0] bitcast_ln165_reg_350;
wire   [63:0] zext_ln165_1_fu_302_p1;
wire  signed [63:0] sext_ln165_fu_266_p1;
reg   [6:0] j_fu_90;
wire   [6:0] add_ln163_fu_226_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_1;
wire   [11:0] zext_ln161_2_cast_fu_208_p1;
wire   [11:0] zext_ln163_fu_232_p1;
wire   [11:0] add_ln165_1_fu_250_p2;
wire   [62:0] zext_ln165_fu_256_p1;
wire  signed [62:0] sext_ln161_cast_fu_204_p1;
wire   [62:0] add_ln165_fu_260_p2;
wire   [2:0] tmp_3_fu_285_p4;
wire   [8:0] tmp_4_fu_294_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_done_reg = 1'b0;
end

srcnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln163_fu_220_p2 == 1'd0))) begin
            j_fu_90 <= add_ln163_fu_226_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_90 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        lshr_ln2_reg_339_pp0_iter1_reg <= lshr_ln2_reg_339;
        trunc_ln163_reg_335_pp0_iter1_reg <= trunc_ln163_reg_335;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        bitcast_ln165_reg_350 <= bitcast_ln165_fu_281_p1;
        lshr_ln2_reg_339_pp0_iter2_reg <= lshr_ln2_reg_339_pp0_iter1_reg;
        lshr_ln2_reg_339_pp0_iter3_reg <= lshr_ln2_reg_339_pp0_iter2_reg;
        lshr_ln2_reg_339_pp0_iter4_reg <= lshr_ln2_reg_339_pp0_iter3_reg;
        lshr_ln2_reg_339_pp0_iter5_reg <= lshr_ln2_reg_339_pp0_iter4_reg;
        lshr_ln2_reg_339_pp0_iter6_reg <= lshr_ln2_reg_339_pp0_iter5_reg;
        lshr_ln2_reg_339_pp0_iter7_reg <= lshr_ln2_reg_339_pp0_iter6_reg;
        lshr_ln2_reg_339_pp0_iter8_reg <= lshr_ln2_reg_339_pp0_iter7_reg;
        lshr_ln2_reg_339_pp0_iter9_reg <= lshr_ln2_reg_339_pp0_iter8_reg;
        trunc_ln163_reg_335_pp0_iter2_reg <= trunc_ln163_reg_335_pp0_iter1_reg;
        trunc_ln163_reg_335_pp0_iter3_reg <= trunc_ln163_reg_335_pp0_iter2_reg;
        trunc_ln163_reg_335_pp0_iter4_reg <= trunc_ln163_reg_335_pp0_iter3_reg;
        trunc_ln163_reg_335_pp0_iter5_reg <= trunc_ln163_reg_335_pp0_iter4_reg;
        trunc_ln163_reg_335_pp0_iter6_reg <= trunc_ln163_reg_335_pp0_iter5_reg;
        trunc_ln163_reg_335_pp0_iter7_reg <= trunc_ln163_reg_335_pp0_iter6_reg;
        trunc_ln163_reg_335_pp0_iter8_reg <= trunc_ln163_reg_335_pp0_iter7_reg;
        trunc_ln163_reg_335_pp0_iter9_reg <= trunc_ln163_reg_335_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln163_fu_220_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_w2_addr_reg_344 <= sext_ln165_fu_266_p1;
        lshr_ln2_reg_339 <= {{ap_sig_allocacmp_j_1[5:1]}};
        trunc_ln163_reg_335 <= trunc_ln163_fu_236_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln163_fu_220_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_90;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv2_weights_local_0_0_ce1 = 1'b1;
    end else begin
        conv2_weights_local_0_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln163_reg_335_pp0_iter9_reg == 1'd0) & (trunc_ln161_2_read_reg_317 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv2_weights_local_0_0_we1 = 1'b1;
    end else begin
        conv2_weights_local_0_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv2_weights_local_0_1_ce1 = 1'b1;
    end else begin
        conv2_weights_local_0_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln163_reg_335_pp0_iter9_reg == 1'd1) & (trunc_ln161_2_read_reg_317 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv2_weights_local_0_1_we1 = 1'b1;
    end else begin
        conv2_weights_local_0_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv2_weights_local_1_0_ce1 = 1'b1;
    end else begin
        conv2_weights_local_1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln163_reg_335_pp0_iter9_reg == 1'd0) & (trunc_ln161_2_read_reg_317 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv2_weights_local_1_0_we1 = 1'b1;
    end else begin
        conv2_weights_local_1_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv2_weights_local_1_1_ce1 = 1'b1;
    end else begin
        conv2_weights_local_1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln163_reg_335_pp0_iter9_reg == 1'd1) & (trunc_ln161_2_read_reg_317 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv2_weights_local_1_1_we1 = 1'b1;
    end else begin
        conv2_weights_local_1_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_w2_blk_n_AR = m_axi_gmem_w2_ARREADY;
    end else begin
        gmem_w2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_w2_blk_n_R = m_axi_gmem_w2_RVALID;
    end else begin
        gmem_w2_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_w2_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_w2_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_w2_RREADY = 1'b1;
    end else begin
        m_axi_gmem_w2_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln163_fu_226_p2 = (ap_sig_allocacmp_j_1 + 7'd1);

assign add_ln165_1_fu_250_p2 = (zext_ln161_2_cast_fu_208_p1 + zext_ln163_fu_232_p1);

assign add_ln165_fu_260_p2 = ($signed(zext_ln165_fu_256_p1) + $signed(sext_ln161_cast_fu_204_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem_w2_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem_w2_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem_w2_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem_w2_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = (m_axi_gmem_w2_RVALID == 1'b0);
end

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln165_fu_281_p1 = m_axi_gmem_w2_RDATA;

assign conv2_weights_local_0_0_address1 = zext_ln165_1_fu_302_p1;

assign conv2_weights_local_0_0_d1 = bitcast_ln165_reg_350;

assign conv2_weights_local_0_1_address1 = zext_ln165_1_fu_302_p1;

assign conv2_weights_local_0_1_d1 = bitcast_ln165_reg_350;

assign conv2_weights_local_1_0_address1 = zext_ln165_1_fu_302_p1;

assign conv2_weights_local_1_0_d1 = bitcast_ln165_reg_350;

assign conv2_weights_local_1_1_address1 = zext_ln165_1_fu_302_p1;

assign conv2_weights_local_1_1_d1 = bitcast_ln165_reg_350;

assign icmp_ln163_fu_220_p2 = ((ap_sig_allocacmp_j_1 == 7'd64) ? 1'b1 : 1'b0);

assign m_axi_gmem_w2_ARADDR = gmem_w2_addr_reg_344;

assign m_axi_gmem_w2_ARBURST = 2'd0;

assign m_axi_gmem_w2_ARCACHE = 4'd0;

assign m_axi_gmem_w2_ARID = 1'd0;

assign m_axi_gmem_w2_ARLEN = 32'd1;

assign m_axi_gmem_w2_ARLOCK = 2'd0;

assign m_axi_gmem_w2_ARPROT = 3'd0;

assign m_axi_gmem_w2_ARQOS = 4'd0;

assign m_axi_gmem_w2_ARREGION = 4'd0;

assign m_axi_gmem_w2_ARSIZE = 3'd0;

assign m_axi_gmem_w2_ARUSER = 1'd0;

assign m_axi_gmem_w2_AWADDR = 64'd0;

assign m_axi_gmem_w2_AWBURST = 2'd0;

assign m_axi_gmem_w2_AWCACHE = 4'd0;

assign m_axi_gmem_w2_AWID = 1'd0;

assign m_axi_gmem_w2_AWLEN = 32'd0;

assign m_axi_gmem_w2_AWLOCK = 2'd0;

assign m_axi_gmem_w2_AWPROT = 3'd0;

assign m_axi_gmem_w2_AWQOS = 4'd0;

assign m_axi_gmem_w2_AWREGION = 4'd0;

assign m_axi_gmem_w2_AWSIZE = 3'd0;

assign m_axi_gmem_w2_AWUSER = 1'd0;

assign m_axi_gmem_w2_AWVALID = 1'b0;

assign m_axi_gmem_w2_BREADY = 1'b0;

assign m_axi_gmem_w2_WDATA = 32'd0;

assign m_axi_gmem_w2_WID = 1'd0;

assign m_axi_gmem_w2_WLAST = 1'b0;

assign m_axi_gmem_w2_WSTRB = 4'd0;

assign m_axi_gmem_w2_WUSER = 1'd0;

assign m_axi_gmem_w2_WVALID = 1'b0;

assign sext_ln161_cast_fu_204_p1 = $signed(sext_ln161);

assign sext_ln165_fu_266_p1 = $signed(add_ln165_fu_260_p2);

assign tmp_3_fu_285_p4 = {{i[4:2]}};

assign tmp_4_fu_294_p4 = {{{tmp_3_fu_285_p4}, {trunc_ln165}}, {lshr_ln2_reg_339_pp0_iter9_reg}};

assign trunc_ln161_2_read_reg_317 = trunc_ln161_2;

assign trunc_ln163_fu_236_p1 = ap_sig_allocacmp_j_1[0:0];

assign zext_ln161_2_cast_fu_208_p1 = zext_ln161_2;

assign zext_ln163_fu_232_p1 = ap_sig_allocacmp_j_1;

assign zext_ln165_1_fu_302_p1 = tmp_4_fu_294_p4;

assign zext_ln165_fu_256_p1 = add_ln165_1_fu_250_p2;

endmodule //srcnn_load_conv2_params_Pipeline_VITIS_LOOP_163_2
