// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module srcnn_conv33 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv2_to_conv3_dout,
        conv2_to_conv3_empty_n,
        conv2_to_conv3_read,
        conv3_weights_address0,
        conv3_weights_ce0,
        conv3_weights_q0,
        conv3_weights_address1,
        conv3_weights_ce1,
        conv3_weights_q1,
        conv3_biases_read,
        layer3_output_tile_address0,
        layer3_output_tile_ce0,
        layer3_output_tile_we0,
        layer3_output_tile_d0,
        layer3_output_tile_q0,
        grp_fu_11819_p_din0,
        grp_fu_11819_p_din1,
        grp_fu_11819_p_opcode,
        grp_fu_11819_p_dout0,
        grp_fu_11819_p_ce,
        grp_fu_11823_p_din0,
        grp_fu_11823_p_din1,
        grp_fu_11823_p_opcode,
        grp_fu_11823_p_dout0,
        grp_fu_11823_p_ce,
        grp_fu_11887_p_din0,
        grp_fu_11887_p_din1,
        grp_fu_11887_p_dout0,
        grp_fu_11887_p_ce,
        grp_fu_11891_p_din0,
        grp_fu_11891_p_din1,
        grp_fu_11891_p_dout0,
        grp_fu_11891_p_ce,
        grp_fu_11955_p_din0,
        grp_fu_11955_p_dout0,
        grp_fu_11955_p_ce,
        grp_generic_fmax_float_s_fu_11962_p_din1,
        grp_generic_fmax_float_s_fu_11962_p_dout0,
        grp_generic_fmax_float_s_fu_11962_p_ready,
        grp_generic_fmin_float_s_fu_11966_p_din1,
        grp_generic_fmin_float_s_fu_11966_p_dout0,
        grp_generic_fmin_float_s_fu_11966_p_ready
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] conv2_to_conv3_dout;
input   conv2_to_conv3_empty_n;
output   conv2_to_conv3_read;
output  [9:0] conv3_weights_address0;
output   conv3_weights_ce0;
input  [31:0] conv3_weights_q0;
output  [9:0] conv3_weights_address1;
output   conv3_weights_ce1;
input  [31:0] conv3_weights_q1;
input  [31:0] conv3_biases_read;
output  [8:0] layer3_output_tile_address0;
output   layer3_output_tile_ce0;
output   layer3_output_tile_we0;
output  [31:0] layer3_output_tile_d0;
input  [31:0] layer3_output_tile_q0;
output  [31:0] grp_fu_11819_p_din0;
output  [31:0] grp_fu_11819_p_din1;
output  [1:0] grp_fu_11819_p_opcode;
input  [31:0] grp_fu_11819_p_dout0;
output   grp_fu_11819_p_ce;
output  [31:0] grp_fu_11823_p_din0;
output  [31:0] grp_fu_11823_p_din1;
output  [1:0] grp_fu_11823_p_opcode;
input  [31:0] grp_fu_11823_p_dout0;
output   grp_fu_11823_p_ce;
output  [31:0] grp_fu_11887_p_din0;
output  [31:0] grp_fu_11887_p_din1;
input  [31:0] grp_fu_11887_p_dout0;
output   grp_fu_11887_p_ce;
output  [31:0] grp_fu_11891_p_din0;
output  [31:0] grp_fu_11891_p_din1;
input  [31:0] grp_fu_11891_p_dout0;
output   grp_fu_11891_p_ce;
output  [31:0] grp_fu_11955_p_din0;
input  [31:0] grp_fu_11955_p_dout0;
output   grp_fu_11955_p_ce;
output  [31:0] grp_generic_fmax_float_s_fu_11962_p_din1;
input  [31:0] grp_generic_fmax_float_s_fu_11962_p_dout0;
input   grp_generic_fmax_float_s_fu_11962_p_ready;
output  [31:0] grp_generic_fmin_float_s_fu_11966_p_din1;
input  [31:0] grp_generic_fmin_float_s_fu_11966_p_dout0;
input   grp_generic_fmin_float_s_fu_11966_p_ready;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg conv2_to_conv3_read;
reg[8:0] layer3_output_tile_address0;
reg layer3_output_tile_ce0;
reg layer3_output_tile_we0;
reg[31:0] layer3_output_tile_d0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] empty_132_fu_65_p1;
reg   [31:0] empty_132_reg_74;
wire    ap_CS_fsm_state2;
reg   [13:0] input_tile_address0;
reg    input_tile_ce0;
reg    input_tile_we0;
wire   [31:0] input_tile_q0;
reg    input_tile_ce1;
wire   [31:0] input_tile_q1;
wire    grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_start;
wire    grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_done;
wire    grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_idle;
wire    grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_ready;
wire    grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_conv2_to_conv3_read;
wire   [13:0] grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_address0;
wire    grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_ce0;
wire    grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_we0;
wire   [31:0] grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_d0;
wire    grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_start;
wire    grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_done;
wire    grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_idle;
wire    grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_ready;
wire   [8:0] grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_address0;
wire    grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_ce0;
wire    grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_we0;
wire   [31:0] grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_d0;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_start;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_done;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_idle;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_ready;
wire   [9:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_address0;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_ce0;
wire   [9:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_address1;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_ce1;
wire   [8:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_address0;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_ce0;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_we0;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_d0;
wire   [13:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_address0;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_ce0;
wire   [13:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_address1;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_ce1;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_din0;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_din1;
wire   [1:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_opcode;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_ce;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_din0;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_din1;
wire   [1:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_opcode;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_ce;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_87_p_din0;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_87_p_din1;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_87_p_ce;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_91_p_din0;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_91_p_din1;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_91_p_ce;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_95_p_din0;
wire    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_95_p_ce;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_generic_fmax_float_s_fu_98_p_din1;
wire   [31:0] grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_generic_fmin_float_s_fu_102_p_din1;
reg    grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_start_reg;
reg    grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_start_reg;
reg   [4:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_fu_79_ce;
reg    grp_fu_83_ce;
reg    grp_fu_87_ce;
reg    grp_fu_91_ce;
reg    grp_fu_95_ce;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_start_reg = 1'b0;
#0 grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_start_reg = 1'b0;
#0 grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_start_reg = 1'b0;
end

srcnn_conv33_input_tile_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 9248 ),
    .AddressWidth( 14 ))
input_tile_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_tile_address0),
    .ce0(input_tile_ce0),
    .we0(input_tile_we0),
    .d0(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_d0),
    .q0(input_tile_q0),
    .address1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_address1),
    .ce1(input_tile_ce1),
    .q1(input_tile_q1)
);

srcnn_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3 grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_start),
    .ap_done(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_done),
    .ap_idle(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_idle),
    .ap_ready(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_ready),
    .conv2_to_conv3_dout(conv2_to_conv3_dout),
    .conv2_to_conv3_empty_n(conv2_to_conv3_empty_n),
    .conv2_to_conv3_read(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_conv2_to_conv3_read),
    .input_tile_address0(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_address0),
    .input_tile_ce0(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_ce0),
    .input_tile_we0(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_we0),
    .input_tile_d0(grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_d0)
);

srcnn_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4 grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_start),
    .ap_done(grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_done),
    .ap_idle(grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_idle),
    .ap_ready(grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_ready),
    .layer3_output_tile_address0(grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_address0),
    .layer3_output_tile_ce0(grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_ce0),
    .layer3_output_tile_we0(grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_we0),
    .layer3_output_tile_d0(grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_d0),
    .empty(empty_132_reg_74)
);

srcnn_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6 grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_start),
    .ap_done(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_done),
    .ap_idle(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_idle),
    .ap_ready(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_ready),
    .conv3_weights_address0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_address0),
    .conv3_weights_ce0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_ce0),
    .conv3_weights_q0(conv3_weights_q0),
    .conv3_weights_address1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_address1),
    .conv3_weights_ce1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_ce1),
    .conv3_weights_q1(conv3_weights_q1),
    .layer3_output_tile_address0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_address0),
    .layer3_output_tile_ce0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_ce0),
    .layer3_output_tile_we0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_we0),
    .layer3_output_tile_d0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_d0),
    .layer3_output_tile_q0(layer3_output_tile_q0),
    .input_tile_address0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_address0),
    .input_tile_ce0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_ce0),
    .input_tile_q0(input_tile_q0),
    .input_tile_address1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_address1),
    .input_tile_ce1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_ce1),
    .input_tile_q1(input_tile_q1),
    .grp_fu_79_p_din0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_din0),
    .grp_fu_79_p_din1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_din1),
    .grp_fu_79_p_opcode(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_opcode),
    .grp_fu_79_p_dout0(grp_fu_11819_p_dout0),
    .grp_fu_79_p_ce(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_ce),
    .grp_fu_83_p_din0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_din0),
    .grp_fu_83_p_din1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_din1),
    .grp_fu_83_p_opcode(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_opcode),
    .grp_fu_83_p_dout0(grp_fu_11823_p_dout0),
    .grp_fu_83_p_ce(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_ce),
    .grp_fu_87_p_din0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_87_p_din0),
    .grp_fu_87_p_din1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_87_p_din1),
    .grp_fu_87_p_dout0(grp_fu_11887_p_dout0),
    .grp_fu_87_p_ce(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_87_p_ce),
    .grp_fu_91_p_din0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_91_p_din0),
    .grp_fu_91_p_din1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_91_p_din1),
    .grp_fu_91_p_dout0(grp_fu_11891_p_dout0),
    .grp_fu_91_p_ce(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_91_p_ce),
    .grp_fu_95_p_din0(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_95_p_din0),
    .grp_fu_95_p_dout0(grp_fu_11955_p_dout0),
    .grp_fu_95_p_ce(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_95_p_ce),
    .grp_generic_fmax_float_s_fu_98_p_din1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_generic_fmax_float_s_fu_98_p_din1),
    .grp_generic_fmax_float_s_fu_98_p_dout0(grp_generic_fmax_float_s_fu_11962_p_dout0),
    .grp_generic_fmax_float_s_fu_98_p_ready(grp_generic_fmax_float_s_fu_11962_p_ready),
    .grp_generic_fmin_float_s_fu_102_p_din1(grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_generic_fmin_float_s_fu_102_p_din1),
    .grp_generic_fmin_float_s_fu_102_p_dout0(grp_generic_fmin_float_s_fu_11966_p_dout0),
    .grp_generic_fmin_float_s_fu_102_p_ready(grp_generic_fmin_float_s_fu_11966_p_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state4) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_ready == 1'b1)) begin
            grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_start_reg <= 1'b1;
        end else if ((grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_ready == 1'b1)) begin
            grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_start_reg <= 1'b1;
        end else if ((grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_ready == 1'b1)) begin
            grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_132_reg_74 <= empty_132_fu_65_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state5) & (grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        conv2_to_conv3_read = grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_conv2_to_conv3_read;
    end else begin
        conv2_to_conv3_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_79_ce = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_ce;
    end else begin
        grp_fu_79_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_83_ce = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_ce;
    end else begin
        grp_fu_83_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_87_ce = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_87_p_ce;
    end else begin
        grp_fu_87_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_91_ce = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_91_p_ce;
    end else begin
        grp_fu_91_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_95_ce = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_95_p_ce;
    end else begin
        grp_fu_95_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_tile_address0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_tile_address0 = grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_address0;
    end else begin
        input_tile_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_tile_ce0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_tile_ce0 = grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_ce0;
    end else begin
        input_tile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_tile_ce1 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_input_tile_ce1;
    end else begin
        input_tile_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_tile_we0 = grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_input_tile_we0;
    end else begin
        input_tile_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        layer3_output_tile_address0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        layer3_output_tile_address0 = grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_address0;
    end else begin
        layer3_output_tile_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        layer3_output_tile_ce0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        layer3_output_tile_ce0 = grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_ce0;
    end else begin
        layer3_output_tile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        layer3_output_tile_d0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        layer3_output_tile_d0 = grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_d0;
    end else begin
        layer3_output_tile_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        layer3_output_tile_we0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_layer3_output_tile_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        layer3_output_tile_we0 = grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_layer3_output_tile_we0;
    end else begin
        layer3_output_tile_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_done == 1'b0) | (grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_done == 1'b0));
end

assign conv3_weights_address0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_address0;

assign conv3_weights_address1 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_address1;

assign conv3_weights_ce0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_ce0;

assign conv3_weights_ce1 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_conv3_weights_ce1;

assign empty_132_fu_65_p1 = conv3_biases_read;

assign grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_start = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_ap_start_reg;

assign grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_start = grp_conv33_Pipeline_OUT_STATIONARY_CONV3_VITIS_LOOP_34_4_fu_49_ap_start_reg;

assign grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_start = grp_conv33_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_VITIS_LOOP_25_3_fu_42_ap_start_reg;

assign grp_fu_11819_p_ce = grp_fu_79_ce;

assign grp_fu_11819_p_din0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_din0;

assign grp_fu_11819_p_din1 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_79_p_din1;

assign grp_fu_11819_p_opcode = 2'd0;

assign grp_fu_11823_p_ce = grp_fu_83_ce;

assign grp_fu_11823_p_din0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_din0;

assign grp_fu_11823_p_din1 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_83_p_din1;

assign grp_fu_11823_p_opcode = 2'd0;

assign grp_fu_11887_p_ce = grp_fu_87_ce;

assign grp_fu_11887_p_din0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_87_p_din0;

assign grp_fu_11887_p_din1 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_87_p_din1;

assign grp_fu_11891_p_ce = grp_fu_91_ce;

assign grp_fu_11891_p_din0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_91_p_din0;

assign grp_fu_11891_p_din1 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_91_p_din1;

assign grp_fu_11955_p_ce = grp_fu_95_ce;

assign grp_fu_11955_p_din0 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_fu_95_p_din0;

assign grp_generic_fmax_float_s_fu_11962_p_din1 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_generic_fmax_float_s_fu_98_p_din1;

assign grp_generic_fmin_float_s_fu_11966_p_din1 = grp_conv33_Pipeline_MAC_CONV3_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_56_grp_generic_fmin_float_s_fu_102_p_din1;

endmodule //srcnn_conv33
