// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module srcnn_conv3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv3_weights_address0,
        conv3_weights_ce0,
        conv3_weights_q0,
        conv3_weights_address1,
        conv3_weights_ce1,
        conv3_weights_q1,
        conv3_biases_0_0_val,
        output_ftmap_address0,
        output_ftmap_ce0,
        output_ftmap_we0,
        output_ftmap_d0,
        layer2_output_address0,
        layer2_output_ce0,
        layer2_output_q0,
        grp_fu_97_p_din0,
        grp_fu_97_p_din1,
        grp_fu_97_p_opcode,
        grp_fu_97_p_dout0,
        grp_fu_97_p_ce,
        grp_fu_108_p_din0,
        grp_fu_108_p_dout0,
        grp_fu_108_p_ce,
        grp_fu_101_p_din0,
        grp_fu_101_p_din1,
        grp_fu_101_p_dout0,
        grp_fu_101_p_ce,
        grp_fu_105_p_din0,
        grp_fu_105_p_dout0,
        grp_fu_105_p_ce
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] conv3_weights_address0;
output   conv3_weights_ce0;
input  [31:0] conv3_weights_q0;
output  [9:0] conv3_weights_address1;
output   conv3_weights_ce1;
input  [31:0] conv3_weights_q1;
input  [31:0] conv3_biases_0_0_val;
output  [15:0] output_ftmap_address0;
output   output_ftmap_ce0;
output   output_ftmap_we0;
output  [31:0] output_ftmap_d0;
output  [20:0] layer2_output_address0;
output   layer2_output_ce0;
input  [31:0] layer2_output_q0;
output  [31:0] grp_fu_97_p_din0;
output  [31:0] grp_fu_97_p_din1;
output  [1:0] grp_fu_97_p_opcode;
input  [31:0] grp_fu_97_p_dout0;
output   grp_fu_97_p_ce;
output  [31:0] grp_fu_108_p_din0;
input  [63:0] grp_fu_108_p_dout0;
output   grp_fu_108_p_ce;
output  [31:0] grp_fu_101_p_din0;
output  [31:0] grp_fu_101_p_din1;
input  [31:0] grp_fu_101_p_dout0;
output   grp_fu_101_p_ce;
output  [31:0] grp_fu_105_p_din0;
input  [63:0] grp_fu_105_p_dout0;
output   grp_fu_105_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_ftmap_ce0;
reg output_ftmap_we0;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] select_ln13_fu_167_p3;
reg   [7:0] select_ln13_reg_368;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln13_fu_137_p2;
wire   [7:0] select_ln13_1_fu_175_p3;
reg   [7:0] select_ln13_1_reg_374;
wire   [31:0] zext_ln13_fu_183_p1;
reg   [63:0] x_assign_3_2_mid2_reg_387;
wire    ap_CS_fsm_state5;
wire   [63:0] bitcast_ln13_fu_209_p1;
reg   [63:0] bitcast_ln13_reg_392;
wire    ap_CS_fsm_state6;
reg   [31:0] y_assign_reg_400;
wire    ap_CS_fsm_state11;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_start;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_done;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_idle;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_ready;
wire   [9:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_address0;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_ce0;
wire   [9:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_address1;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_ce1;
wire   [31:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_convolution_out;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_convolution_out_ap_vld;
wire   [20:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_layer2_output_address0;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_layer2_output_ce0;
wire   [31:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_din0;
wire   [31:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_din1;
wire   [1:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_opcode;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_ce;
wire   [31:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_407_p_din0;
wire   [31:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_407_p_din1;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_407_p_ce;
wire  signed [31:0] grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_411_p_din0;
wire    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_411_p_ce;
reg    grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_start_reg;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln37_2_fu_242_p1;
wire    ap_CS_fsm_state12;
reg   [7:0] out_feat_x_fu_64;
wire   [7:0] add_ln15_fu_188_p2;
reg   [7:0] out_feat_y_fu_68;
reg   [15:0] indvar_flatten6_fu_72;
wire   [15:0] add_ln13_1_fu_143_p2;
wire    ap_CS_fsm_state8;
reg   [31:0] grp_fu_112_p0;
reg   [31:0] grp_fu_112_p1;
wire   [0:0] icmp_ln15_fu_161_p2;
wire   [7:0] add_ln13_fu_155_p2;
wire   [15:0] tmp_fu_220_p3;
wire   [15:0] zext_ln37_fu_217_p1;
wire   [15:0] sub_ln37_fu_227_p2;
wire   [15:0] zext_ln37_1_fu_233_p1;
wire   [15:0] add_ln37_fu_236_p2;
wire   [31:0] data_fu_247_p1;
wire   [7:0] y_fp_exp_fu_250_p4;
wire   [22:0] y_fp_sig_fu_260_p1;
wire   [0:0] icmp_ln25_fu_264_p2;
wire   [0:0] icmp_ln25_2_fu_270_p2;
wire   [0:0] ymaggreater_fu_294_p2;
wire   [0:0] and_ln25_fu_276_p2;
wire   [31:0] res_fu_300_p3;
wire   [0:0] icmp_ln18_7_fu_282_p2;
wire   [0:0] xor_ln18_fu_288_p2;
wire   [31:0] select_ln25_fu_307_p3;
wire   [0:0] and_ln18_fu_314_p2;
wire   [31:0] bitcast_ln37_fu_320_p1;
reg    grp_fu_112_ce;
reg    grp_fu_407_ce;
reg    grp_fu_411_ce;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_start_reg = 1'b0;
end

srcnn_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5 grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_start),
    .ap_done(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_done),
    .ap_idle(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_idle),
    .ap_ready(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_ready),
    .conv3_weights_address0(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_address0),
    .conv3_weights_ce0(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_ce0),
    .conv3_weights_q0(conv3_weights_q0),
    .conv3_weights_address1(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_address1),
    .conv3_weights_ce1(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_ce1),
    .conv3_weights_q1(conv3_weights_q1),
    .zext_ln26(select_ln13_reg_368),
    .zext_ln13_1(select_ln13_1_reg_374),
    .bitcast_ln13(bitcast_ln13_reg_392),
    .select_ln13_1(select_ln13_1_reg_374),
    .convolution_out(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_convolution_out),
    .convolution_out_ap_vld(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_convolution_out_ap_vld),
    .layer2_output_address0(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_layer2_output_address0),
    .layer2_output_ce0(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_layer2_output_ce0),
    .layer2_output_q0(layer2_output_q0),
    .grp_fu_112_p_din0(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_din0),
    .grp_fu_112_p_din1(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_din1),
    .grp_fu_112_p_opcode(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_opcode),
    .grp_fu_112_p_dout0(grp_fu_97_p_dout0),
    .grp_fu_112_p_ce(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_ce),
    .grp_fu_407_p_din0(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_407_p_din0),
    .grp_fu_407_p_din1(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_407_p_din1),
    .grp_fu_407_p_dout0(grp_fu_101_p_dout0),
    .grp_fu_407_p_ce(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_407_p_ce),
    .grp_fu_411_p_din0(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_411_p_din0),
    .grp_fu_411_p_dout0(grp_fu_105_p_dout0),
    .grp_fu_411_p_ce(grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_411_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_start_reg <= 1'b1;
        end else if ((grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_ready == 1'b1)) begin
            grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten6_fu_72 <= 16'd0;
    end else if (((icmp_ln13_fu_137_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten6_fu_72 <= add_ln13_1_fu_143_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        out_feat_x_fu_64 <= 8'd0;
    end else if (((icmp_ln13_fu_137_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_feat_x_fu_64 <= add_ln15_fu_188_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        out_feat_y_fu_68 <= 8'd0;
    end else if (((icmp_ln13_fu_137_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_feat_y_fu_68 <= select_ln13_1_fu_175_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        bitcast_ln13_reg_392 <= bitcast_ln13_fu_209_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_fu_137_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        select_ln13_1_reg_374 <= select_ln13_1_fu_175_p3;
        select_ln13_reg_368 <= select_ln13_fu_167_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_assign_3_2_mid2_reg_387 <= grp_fu_108_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        y_assign_reg_400 <= grp_fu_97_p_dout0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln13_fu_137_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_fu_137_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_112_ce = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_ce;
    end else begin
        grp_fu_112_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_112_p0 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_112_p0 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_convolution_out;
    end else begin
        grp_fu_112_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_112_p1 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_112_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_112_p1 = conv3_biases_0_0_val;
    end else begin
        grp_fu_112_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_407_ce = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_407_p_ce;
    end else begin
        grp_fu_407_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_411_ce = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_411_p_ce;
    end else begin
        grp_fu_411_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        output_ftmap_ce0 = 1'b1;
    end else begin
        output_ftmap_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        output_ftmap_we0 = 1'b1;
    end else begin
        output_ftmap_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln13_fu_137_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_1_fu_143_p2 = (indvar_flatten6_fu_72 + 16'd1);

assign add_ln13_fu_155_p2 = (out_feat_y_fu_68 + 8'd1);

assign add_ln15_fu_188_p2 = (select_ln13_fu_167_p3 + 8'd1);

assign add_ln37_fu_236_p2 = (sub_ln37_fu_227_p2 + zext_ln37_1_fu_233_p1);

assign and_ln18_fu_314_p2 = (xor_ln18_fu_288_p2 & icmp_ln18_7_fu_282_p2);

assign and_ln25_fu_276_p2 = (icmp_ln25_fu_264_p2 & icmp_ln25_2_fu_270_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign bitcast_ln13_fu_209_p1 = x_assign_3_2_mid2_reg_387;

assign bitcast_ln37_fu_320_p1 = select_ln25_fu_307_p3;

assign conv3_weights_address0 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_address0;

assign conv3_weights_address1 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_address1;

assign conv3_weights_ce0 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_ce0;

assign conv3_weights_ce1 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_conv3_weights_ce1;

assign data_fu_247_p1 = y_assign_reg_400;

assign grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_start = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_ap_start_reg;

assign grp_fu_101_p_ce = grp_fu_407_ce;

assign grp_fu_101_p_din0 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_407_p_din0;

assign grp_fu_101_p_din1 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_407_p_din1;

assign grp_fu_105_p_ce = grp_fu_411_ce;

assign grp_fu_105_p_din0 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_grp_fu_411_p_din0;

assign grp_fu_108_p_ce = 1'b1;

assign grp_fu_108_p_din0 = zext_ln13_fu_183_p1;

assign grp_fu_97_p_ce = grp_fu_112_ce;

assign grp_fu_97_p_din0 = grp_fu_112_p0;

assign grp_fu_97_p_din1 = grp_fu_112_p1;

assign grp_fu_97_p_opcode = 2'd0;

assign icmp_ln13_fu_137_p2 = ((indvar_flatten6_fu_72 == 16'd65025) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_161_p2 = ((out_feat_x_fu_64 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln18_7_fu_282_p2 = ((y_fp_exp_fu_250_p4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln25_2_fu_270_p2 = ((y_fp_sig_fu_260_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_264_p2 = ((y_fp_exp_fu_250_p4 == 8'd0) ? 1'b1 : 1'b0);

assign layer2_output_address0 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_layer2_output_address0;

assign layer2_output_ce0 = grp_conv3_Pipeline_VITIS_LOOP_26_4_VITIS_LOOP_28_5_fu_99_layer2_output_ce0;

assign output_ftmap_address0 = zext_ln37_2_fu_242_p1;

assign output_ftmap_d0 = ((and_ln18_fu_314_p2[0:0] == 1'b1) ? 32'd0 : bitcast_ln37_fu_320_p1);

assign res_fu_300_p3 = ((ymaggreater_fu_294_p2[0:0] == 1'b1) ? y_assign_reg_400 : 32'd0);

assign select_ln13_1_fu_175_p3 = ((icmp_ln15_fu_161_p2[0:0] == 1'b1) ? add_ln13_fu_155_p2 : out_feat_y_fu_68);

assign select_ln13_fu_167_p3 = ((icmp_ln15_fu_161_p2[0:0] == 1'b1) ? 8'd0 : out_feat_x_fu_64);

assign select_ln25_fu_307_p3 = ((and_ln25_fu_276_p2[0:0] == 1'b1) ? y_assign_reg_400 : res_fu_300_p3);

assign sub_ln37_fu_227_p2 = (tmp_fu_220_p3 - zext_ln37_fu_217_p1);

assign tmp_fu_220_p3 = {{select_ln13_1_reg_374}, {8'd0}};

assign xor_ln18_fu_288_p2 = (icmp_ln25_2_fu_270_p2 ^ 1'd1);

assign y_fp_exp_fu_250_p4 = {{data_fu_247_p1[30:23]}};

assign y_fp_sig_fu_260_p1 = data_fu_247_p1[22:0];

assign ymaggreater_fu_294_p2 = (($signed(data_fu_247_p1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign zext_ln13_fu_183_p1 = select_ln13_1_fu_175_p3;

assign zext_ln37_1_fu_233_p1 = select_ln13_reg_368;

assign zext_ln37_2_fu_242_p1 = add_ln37_fu_236_p2;

assign zext_ln37_fu_217_p1 = select_ln13_1_reg_374;

endmodule //srcnn_conv3
